/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as PharmacistRouteImport } from './routes/pharmacist'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as CategoryCategoryRouteImport } from './routes/category/$category'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin/index'
import { Route as SuperadminLoginRouteImport } from './routes/superadmin/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistRoute = PharmacistRouteImport.update({
  id: '/pharmacist',
  path: '/pharmacist',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminLoginRoute = SuperadminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SuperadminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/doctor': typeof DoctorRoute
  '/pharmacist': typeof PharmacistRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/category/$category': typeof CategoryCategoryRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/doctor': typeof DoctorRoute
  '/pharmacist': typeof PharmacistRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin': typeof SuperadminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/doctor': typeof DoctorRoute
  '/pharmacist': typeof PharmacistRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/category/$category': typeof CategoryCategoryRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/doctor'
    | '/pharmacist'
    | '/superadmin'
    | '/category/$category'
    | '/products/$productId'
    | '/superadmin/login'
    | '/superadmin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/doctor'
    | '/pharmacist'
    | '/category/$category'
    | '/products/$productId'
    | '/superadmin/login'
    | '/superadmin'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/doctor'
    | '/pharmacist'
    | '/superadmin'
    | '/category/$category'
    | '/products/$productId'
    | '/superadmin/login'
    | '/superadmin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  DoctorRoute: typeof DoctorRoute
  PharmacistRoute: typeof PharmacistRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacist': {
      id: '/pharmacist'
      path: '/pharmacist'
      fullPath: '/pharmacist'
      preLoaderRoute: typeof PharmacistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/login': {
      id: '/superadmin/login'
      path: '/login'
      fullPath: '/superadmin/login'
      preLoaderRoute: typeof SuperadminLoginRouteImport
      parentRoute: typeof SuperadminRoute
    }
  }
}

interface SuperadminRouteChildren {
  SuperadminLoginRoute: typeof SuperadminLoginRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminLoginRoute: SuperadminLoginRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  DoctorRoute: DoctorRoute,
  PharmacistRoute: PharmacistRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  CategoryCategoryRoute: CategoryCategoryRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
